'''
test Visualize a input json file generated by Torch Profiler
'''

from perflowai.reader import TorchProfilerTraceReader
from perflowai.visualizer import TraceVisiualizer
from perflowai.core import EventType
import os



def test_jsonvisualization():
    tp_reader = TorchProfilerTraceReader('./tests/example_trace/out-1024.json')
    tp_reader.read(event_types =  [EventType.FWD, EventType.BWD])
    output = tp_reader.get_outputs()
    trace = output[0]
    visualizer = TraceVisiualizer(trace)
    visualizer.visualize()
    assert os.path.isfile("./trace.svg")
