#!/usr/bin/env python3
"""Refresh consolidated live view of PADOC bench experiments.

Writes ``report/exp/LIVE_SNAPSHOT.md`` (overwritten each run) with:
  * UTC timestamp
  * Counts by status (running / done / failed)
  * Latest N experiment rows from ``report/exp/*/meta.json``
  * Presence + mtime of ``report/exp_results/{C20–C26,D20–D26}*.{md,json,csv}``

Intended to be run every 60–120s from a nohup loop alongside ``watch_fill.py``.
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXP = ROOT / "report" / "exp"
OUT = EXP / "LIVE_SNAPSHOT.md"
RES = ROOT / "report" / "exp_results"

BATCH_NAMES = [
    "C20_compress_subset8",
    "C21_compress_subset32",
    "C22_compress_subset64",
    "C23_compress_leworldmodel",
    "C24_compress_unifolm",
    "C25_compress_qwen3_full_padoc",
    "C26_compress_llama_full_padoc",
    "D20_analyze_subset8",
    "D21_analyze_subset32",
    "D22_analyze_subset64",
    "D23_analyze_leworldmodel",
    "D24_analyze_unifolm",
    "D25_analyze_qwen3_full_padoc",
    "D26_analyze_llama_full_padoc",
]


def load_metas() -> list[dict]:
    rows: list[dict] = []
    if not EXP.is_dir():
        return rows
    for d in EXP.iterdir():
        if not d.is_dir() or d.name.startswith("."):
            continue
        mp = d / "meta.json"
        if not mp.is_file():
            continue
        try:
            m = json.loads(mp.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            continue
        m["_dir"] = d.name
        rows.append(m)
    rows.sort(key=lambda r: r.get("start_epoch") or 0, reverse=True)
    return rows


def fmt_meta_row(m: dict) -> str:
    st = m.get("status", "?")
    name = str(m.get("name", m.get("_dir", "?")))[:44]
    ec = m.get("exit_code")
    ec_s = "" if ec is None else str(ec)
    el = m.get("elapsed_seconds")
    el_s = "-" if el is None else f"{int(el)}s"
    if st == "running":
        el_s = "…"
    return f"| `{name}` | {st} | {ec_s} | {el_s} | `{m.get('_dir', '')}` |"


def artifact_table() -> str:
    lines = ["", "## Batch outputs (`report/exp_results/`)", "", "| artifact | json | md |", "| --- | --- | --- |"]
    if not RES.is_dir():
        lines.append("| (exp_results missing) | | |")
        return "\n".join(lines)
    for base in BATCH_NAMES:
        js = RES / f"{base}.json"
        md = RES / f"{base}.md"
        jm = _mtime(js)
        mm = _mtime(md)
        lines.append(f"| `{base}` | {jm} | {mm} |")
    return "\n".join(lines)


def _mtime(p: Path) -> str:
    if not p.is_file():
        return "—"
    try:
        ts = p.stat().st_mtime
        return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%m-%d %H:%M UTC")
    except OSError:
        return "?"


def main() -> int:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    rows = load_metas()
    counts: dict[str, int] = {}
    for m in rows:
        s = m.get("status") or "?"
        counts[s] = counts.get(s, 0) + 1

    lines = [
        "# PADOC experiments — live snapshot",
        "",
        f"_Auto-generated {now}. Regenerated by `scripts/exp/refresh_snapshot.py`._",
        "",
        "## Status counts (`report/exp/*/meta.json`)",
        "",
        "| status | count |",
        "| --- | ---: |",
    ]
    for k in sorted(counts.keys()):
        lines.append(f"| {k} | {counts[k]} |")
    lines += [
        "",
        "## Latest experiments (most recent first, max 48)",
        "",
        "| name | status | exit | elapsed | dir |",
        "| --- | --- | --- | --- | --- |",
    ]
    for m in rows[:48]:
        lines.append(fmt_meta_row(m))
    lines.append(artifact_table())
    lines += [
        "",
        "## Commands",
        "",
        "```bash",
        "python3 scripts/exp/status.py --running-only --watch 8",
        "tmux attach -t padoc",
        "```",
        "",
    ]
    EXP.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
